### PR TITLE
Prevents breaking during mapping of input types with defaults from enums

### PR DESCRIPTION
**Pull request by DServy**
## PR Checklist:
- [ X] I have run `npm test` locally and all tests are passing.
- [ X] I have added/updated tests for any new behavior.
  
- [ ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
  
- [ X] If this is a version update, have you updated the CHANGELOG.md?

## PR Description
Allows for optional enum based array types with default values 

E.g 
`orderBy: [MessagesOrderBy!] = [PRIMARY_KEY_ASC]`

Useful for autogen based schema files from something like Postgraphile

### CODE REVIEW

**Comment by laurenjs827** [comment]
> * link

**Review by schwer — APPROVED** [review]

**Review by schwer — COMMENTED** [review]
This looks good. I would appreciate if you'd create an issue first. As part of creating an issue, make sure to supply a deeper explanation of what this PR is seeking to fix. Specifically, I'd really like to see something like:

Currently the behavior is this....
If we fix this issue, we'd expect the behavior to be....

**Comment by DServy** [comment]
@schwer I didn't think it's a big enough of a change to warrant a huge issue tracking since it basically just makes it work for valid openAPI specs. It's just null checks. Would really appreciate this moving forward and being incorporated into a release soon.

**Comment by schwer** [comment]
Fixes #71

**Comment by schwer** [comment]
Incorporated into a separate PR because the github actions weren't running as expected.

**Pull request closed without merging**
